version: "3.1"

services:
        wordpress:
                image: wordpress
                restart: always
                depends_on:
                        - db
                volumes:
                        - ./sage:/var/www/html/wp-content/themes/
                ports:
                        - 8080:80
                environment:
                        WORDPRESS_DB_HOST: db
                        WORDPRESS_DB_USER: user
                        WORDPRESS_DB_PASSWORD: password
                        WORDPRESS_DB_NAME: wordpress

        db:
                image: mysql:5.7
                restart: always
                volumes:
                        - mysql-data:/var/lib/mysql
                environment:
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: user
                        MYSQL_PASSWORD: password
                        MYSQL_RANDOM_ROOT_PASSWORD: "1"
                networks:
                        - wpsite
        phpmyadmin:
                depends_on:
                        - db
                image: phpmyadmin/phpmyadmin
                restart: always
                ports:
                        - 8080:80
                environment:
                        PMA_HOST: db
                        MYSQL_ROOT_PASSWORD: password
                networks:
                        - wpsite
volumes:
        mysql-data:
networks:
        wpsite:
